version: '3.3'
services:
  sql:
    image: "mariadb:10.3"
    restart: 'always'
    volumes:
      - ./data:/var/lib/mysql/
      - ./logs:/var/log/mysql/
      - ./snapshots:/var/mysql/snapshots/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
  # web:
  #   container_name: web 
  #   build: .
  #   ports:
  #     - "8080:8080"
  #     - "8085:8085"
  #   volumes:
  #     - .:/usr/src/app
  #   stdin_open: true
  #   tty: true
