version: '3.3'
services:
  sql:
    image: "mariadb:10.3"
    restart: 'always'
    # volumes:
    #   - ./data:/var/lib/mysql/
    #   - ./logs:/var/log/mysql/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
  server:
    container_name: server 
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - "sql"
    stdin_open: true
    tty: true
